### ISSUE TITLE
cannot find the tv card in HA

### ISSUE THREAD

**Issue by jpcugv** [madmicio/Apple-Tv-Card#2]
I automatically installed this card according to your introduction, and the HA folder already has this file, but the strange thing is that I can't find the apple tv card in the lovelace card, and I didn't find anything wrong.

**Comment by jpcugv** [comment]
Secondly I also tried to manually download this js file to HA and configure it, but still can't find this card

**Comment by madmicio** [comment]
try to upgrade.
