### ISSUE TITLE
Text moved & sources do not work at my configuration

### ISSUE THREAD

**Issue by beathoch** [madmicio/Apple-Tv-Card#3]
Hi madmicio

Thank you very much for the Apple TV Card. I've been waiting for such a long time.
Basically I could install it and operate the Apple TV works perfectly.

But I have two problems:

1. The seeming rolling text above the navigation wheel is shifted to the right and the text is far too large.
2. The sources buttons don't work, what do I do wrong?

`type: custom:apple-tv-card
name: Apple TV
entity: media_player.apple_tv_2
remote: remote.apple_tv_2
full_screen: true
sources:
  - source_name: Netflix
  - source_name: Zattoo
  - source_name: Prime Video
  - source_name: YouTube
  - image: /local/custom_components/Apple-Tv-Card/dist/logo/netflix.png
    source_name: Netflix
  - image: /local/custom_components/Apple-Tv-Card/dist/logo/zattoo.png
    source_name: Zattoo
  - image: /local/custom_components/Apple-Tv-Card/dist/logo/prime.png
    source_name: Prime Video
  - image: /local/custom_components/Apple-Tv-Card/dist/logo/youtube.png
    source_name: YouTube
`

**Comment by madmicio** [comment]
can you post a photo of the text problem?  do you use the app or fully kiosk?  you can also post a pastebin with the configuration you have used.  Let me know, I'll be happy to help you

**Comment by beathoch** [comment]
<img width="1382" alt="Bildschirmfoto 2023-10-01 um 13 32 52" src="https://github.com/madmicio/Apple-Tv-Card/assets/56131389/1fda4157-cca0-4121-ba96-09a676e12945">

**Comment by beathoch** [comment]
I have try both kiosk and card in layout, on both the text goes out from the right frame.

In Layout RAW Settings:
kiosk_mode:
    hide_header: true
    hide_sidebar: false
    ignore_entity_settings: true

**Comment by beathoch** [comment]
![IMG_1179](https://github.com/madmicio/Apple-Tv-Card/assets/56131389/cc043d1c-e7b2-4b94-a9b7-51d62a2f604d)

**Comment by madmicio** [comment]
Oh sorry!  I forgot to write the instructions on how to load the font in the home assistant resources.  I will correct the information in the readme as soon as possible

**Comment by madmicio** [comment]
please update and follow the instructions for installing the font

**Comment by beathoch** [comment]
Thank you for the font instruction, it looks now better, but still very large. Where can I reduce the font size?

**Comment by beathoch** [comment]
![image](https://github.com/madmicio/Apple-Tv-Card/assets/56131389/0391a626-ea93-4585-87e6-a6899b5cb2b1)

**Comment by madmicio** [comment]
This behavior surprises me a lot. I tested the card in Chrome, Edge in Windows OS. companion app and fully kiosk on Android, companion app on iOS.
can you tell me what OS you are using, what browser or app you are using?
version of Home assistant?

**Comment by beathoch** [comment]
I use the HA Client on iOS on iPhone and iPad and also Safari on my MacMini, all the device have installed the newest OS.
The lettering above is not important to me if you can hide it, it would be enough for me.

The sources buttons don't work either. Here always comes the message: media_player/select_source. Entity media_player.apple_tv_2 does not support this service.

If you could hide the font above and the 6 buttons, that would be enough for me. Hide, I mean, if you could remove that in the code. Is there any possibility?

or why can I not see any entities for my Apple TV (latest generation)?

I use Mushroom, maybe this is a problem?
